### ISSUE TITLE
VPN Unlimited issue

### ISSUE THREAD

**Issue by CapeData** [Zomboided/service.vpn.manager#8] opened 2016-11-06 18:21 UTC
Installed addon on Librelec 7 without any problems, however, cannot connect to VPNunlimited servers. The zip file containing the data consists of (2) different certificates and one key. I extracted them and created the corresponding files per the instruction, but validation fails (I tried both certificates). 

Log file:

13:16:34 T:544990363872  NOTICE: VPN Mgr : (platform.py) VPN log file start >>>
13:16:34 T:544990363872  NOTICE: Sun Nov  6 13:14:34 2016 OpenVPN 2.3.10 aarch64-libreelec-linux-gnueabi [SSL (OpenSSL)] [LZO] [EPOLL] [IPv6] built on Aug 20 2016
13:16:34 T:544990363872  NOTICE: Sun Nov  6 13:14:34 2016 library versions: LibreSSL 2.2.6, LZO 2.09
13:16:34 T:544990363872  NOTICE: Sun Nov  6 13:14:34 2016 Cannot load certificate file /storage/.kodi/userdata/addon_data/service.vpn.manager/VPNUnlimited/user.crt: error:0906D06C:PEM routines:PEM_read_bio:no start line: error:140AD009:SSL routines:SSL_CTX_use_certificate_file:PEM lib
13:16:34 T:544990363872  NOTICE: Sun Nov  6 13:14:34 2016 Exiting due to fatal error
13:16:34 T:544990363872  NOTICE: VPN Mgr : (platform.py) <<< VPN log file end
13:16:34 T:544990363872  NOTICE: VPN Mgr : (managefiles.py) Copying log file to /storage/downloads/kodi_16-11-06_13-16-34.log.  Using version 2.2.1

**Comment by Zomboided** [comment] 2016-11-07 08:41
Looks like a user certificate issue to me.  This file will have been uploaded for you during the connection process, but it's suggesting that it's not there/readable.

/storage/.kodi/userdata/addon_data/service.vpn.manager/VPNUnlimited/user.crt

Check the location to see if the file is there, then check the contents to see that it's what's expceting in the user.crt file (compare with the example in the wiki)

If you need to change it, you'll have to use the settings/utilities/manage keys option in the GUI and delete all of the keys.

Also this provider is untested so even after getting this part right you might still see another issue we'd need to work through.

**Comment by CapeData** [comment] 2016-11-07 13:26
Thanks for the reply.

I did some searching and read where another vpn unlimited user had reverted 
to v1.5 of the manager and it worked. I did the same, and was able to 
connect using the same crt and key files I had attempted to use with v2.21.

**Comment by RobertinBrighton** [comment] 2017-01-01 16:07
Hi,

Just got VPNUnlimited to work using 2.2.1

a) ensure you use the country information provided by VPNUnlimited
b) select log-in country to create all needed files (as each country is unique)
c) use selected country information from the *.ovpn file as follows:
    1st certificate section is the ca.crt and is not needed (from <ca> to <\ca>)  
    2nd certificate section is the user certificate which needs to be copied ignoring <cert> and <\cert> into a file named user.crt
    3rd is the user key section which needs to be copied ignoring <key> and <\keycert> into
    a file named user.key   
d) copy files to USB for use in VPN Manager
e) set-up VPNUnlimited with user and pass word blank and select first VPN Connection using the country you got the .crt and .key from
f) check country file for the following content:

client
dev tun
reneg-sec 0
persist-tun
persist-key
ping 5
ping-exit 30
nobind
comp-lzo adaptive
remote-random
ns-cert-type server
route-metric 1
ca C:\\Users\\#####\\AppData\\Roaming\\Kodi\\addons\\service.vpn.manager\\VPNUnlimited\\ca.crt
cert C:\\Users\\#####\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\service.vpn.manager\\VPNUnlimited\\user.crt
key C:\\Users\\#####\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\service.vpn.manager\\VPNUnlimited\\user.key
remote ??.vpnunlimitedapp.com
proto udp

##### = your user name in windows
?? = country code 

Worked for me based on minimal testing 

BR Robert

**Comment by Zomboided** [comment] 2017-01-01 19:36
You don't need to write a conversion program, the addon will generate the right things if I get the definitions right.  Can you confirm for me that the ca.crt never changes and that you've seen different user.crt and user.key used for different locations and I'll fix this so it works fine.

**Comment by RobertinBrighton** [comment] 2017-01-02 10:06
Hi,

 

I can confirm that the CA file stays the same. Rest is and must be differentas you otherwise get too many error messages on screen while watching.  Ran file compare to validate before I got it to work.  

 

VPNUnlimited provided me with a set which has all required info in the country file. That is CA, CERT and Key info. The files where named “e-mail address_cc_nnann.ovpn”

 

cc= country code

nnann=looks irrelevant

 

I suspect these could be used as is provided:

 

a)      Your program does not look for the CRT and KEY files

b)      Can handle the <ca> </ca> + <cert </cert> +  <key> </key> identifiers which defines the log-in keys

c)       Can be renamed so they are easier to load from your GUI 

 

Well it is x-mas time still :)

Their VPN Manager must not be used when using your program.

 

BR Robert

**Comment by RobertinBrighton** [comment] 2017-01-02 10:10
Hi Again

 

Once you got an update, I can test it for you before release if needed.

 

Br Robert

**Comment by Zomboided** [comment] 2017-01-02 11:25
Try this https://github.com/Zomboided/service.vpn.manager/releases/tag/2.3.1
You should reset your ovpn after installing it.
I've added the ability to extract the key and cert file from an ovpn, and I've changed VPN Unlimited to be a unique key/cert per connection, rather than the same key/cert for all connections.
When you connect, you shoudl be asked for the key or ovpn for that connection.
If it fails, do you wanna PM me on the libreELEC forum (zomboided) and we'll get a dialog going over email.

**Comment by skoBuffs** [comment] 2017-01-06 06:09
hi, 
Im wondering how this went struggling atm and wondering if 2.3.1 was the solution and if so how I can implement it.

Sko

**Comment by Zomboided** [comment] 2017-01-06 17:54
Fixed in 2.4.0, in testing currently.

**Closed by Zomboided** 2017-01-06 17:54 UTC

**Comment by skoBuffs** [comment] 2017-01-06 20:08
Is 2.4.0 the solution to this issue?

sko

**Comment by RobertinBrighton** [comment] 2017-01-07 13:24
Tested and now working on my system

**Comment by person-51** [comment] 2017-01-15 23:28
Regarding the user cert/key, are these to be generated on the LibreElec box itself? Would be my understanding the key (private) would remain on the box while the user.crt (public) is used to auth to VPNUnlimited Gateway.

**Comment by person-51** [comment] 2017-01-16 00:15
Nevermind, just have to email support for them and get the .ovpn files.
