### ISSUE TITLE
Verify Error using Windscribe VPN

### ISSUE THREAD

**Issue by demircis** [Zomboided/service.vpn.manager#48] opened 2017-02-11 13:25 UTC
There seems to be an error with the Windscribe setup. Looking at the VPN log, it says there is a format error in the notAfter field of the certificate. You can find the full log here: http://paste.ubuntu.com/23973703/

I checked the username and password multiple times, so I don't think that the problem lies there.

**Comment by Zomboided** [comment] 2017-02-11 17:28
Are you using a free or pro account?

**Comment by Zomboided** [comment] 2017-02-12 10:07
Windscribe gave me a pro account to add support so I've just used it to try and connect without problems (albeit on Windows).  I've looked at the ca and tls certs and they've not changed either.  Assuming you're using your Windscribe 'credentials' rather than your login (which I think you are because otherwise you get auth failure), then I'm not sure what the problem is.  It looks like it can't read the ca file.  Either there's been an install problem or there's a network problem.  See here https://github.com/Zomboided/service.vpn.manager/wiki/10.-Trouble-Shooting#debugging-vpn-problems

Assuming you're on the latest version, you could also try switching off ping and the up/down scripts
https://github.com/Zomboided/service.vpn.manager/wiki/06.-Debug-Options#enable-updown-scripts
and
https://github.com/Zomboided/service.vpn.manager/wiki/06.-Debug-Options#check-connection-with-ping

If this isn't a network or install problem and you find there are other issues caused by the add-on please post up what they are so I can look at fixing them.

**Comment by demircis** [comment] 2017-02-12 13:22
I tried everything you pointed out, and also reinstalled the addon with no success. I looked up what kind of error this notAfter format error is, and I found this on the OpenSSL wiki:

**14 X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD: format error in certificate's notAfter field**
the certificate notAfter field contains an invalid time.

So maybe it has to do with using the correct timezone or something like that?
It's really weird because the addon worked previously, and now after updating LibreELEC to 7.95.3 with Kodi 17.0, it doesn't work.

**Comment by Zomboided** [comment] 2017-02-12 13:32
I wondered if it was a time problem but I checked the log and it looked valid. I'm using an ntp server if that's the difference here?

**Comment by demircis** [comment] 2017-02-12 13:50
I set the ntp servers manually in the LibreELEC configuration, still it reports the same error. I will try to downgrade to the last version of the addon I used when it worked, I think it was 2.4.0. If that doesn't work, it most likely has to do with the update to the new LibreELEC version, since it worked before.

**Comment by dawez** [comment] 2017-02-12 13:54
The root cause of the problem is a 2038 bug that exists in the 32 bit system see here: https://en.wikipedia.org/wiki/Year_2038_problem . Basically the certificate from Windscribe is expiring in 2040 which when parsed by LibreSSL is giving a negative value this cause the error then. There is a discussion taking place here: https://forum.libreelec.tv/thread-1460.html. At the moment the possible solutions are:

1. Downgrade to previous version of LibreElec [one that uses openSSL instead].
2. Use another provider that use a certificate that expires before 2038.
3. Use a docker based solution which will allow to have openVPN and openSSL in a container

**Comment by Zomboided** [comment] 2017-02-12 14:03
That's helpful info, thanks.  I'll add it to my debug page and close this issue (as it's not a problem with my add-on)

**Closed by Zomboided** 2017-02-12 14:03 UTC

**Comment by zayfodbbox** [comment] 2017-05-03 21:38
Additonal info....this is LE8.0.1 version RPi2.arm...if that helps....not sure if the cert expiration bug still exists in the openssl version being used.

**Comment by Zomboided** [comment] 2017-05-04 06:51
Yes, it's broken in all 8.x levels currently.  I have no clue when it'll be
fixed.

**Comment by ecmaia** [comment] 2017-11-15 22:26
Windscribe Password: 
API Error: Could not log in with provided credentials
