### ISSUE TITLE
Spaces in Windows Usernames

### ISSUE THREAD

**Issue by Gitarist2018** [Zomboided/service.vpn.manager#186] opened 2018-10-30 16:39 UTC
Setting up a VPN-Connection via the wizard always failed. I got an authentication error (24:auth-user-login). 
I guess it was because of the space (caused by my username) in the auth-user-pass line of the created ovpn-file. 

To get it working I created my own ovpn-file and an auth-user-pass directory containing no spaces. Afterwards I imported this file without optimazions through service.vpn.manager.

**Comment by Zomboided** [comment] 2018-10-30 17:36
Where was the space in your user name?  Leading and trailing spaces are
stripped.
DId you view the generated PASS.txt file to confirm your theory or are you
guessing at this being the cause?

**Comment by Gitarist2018** [comment] 2018-10-30 20:32
The space is in the middle (between First Name and Last Name). Yes I viewed the pass file but couldn‘t recognize anything extraordinary. It just contained the 2 lines for username and password (I guess scrambeled). But when I checked the generated ovpn file the path to pass.txt contained the space mentioned above and it wasn’t written within „“-signs, which is often a problem in windows scripts (the subfolders were of course seperated through //-signs). So this was the most obvious answer for my problem to me. 

BTW: I like your Addon very much.

**Comment by Zomboided** [comment] 2018-10-30 21:02
So the space that was causing you an issue was in your windows path name?
Just so I'm clear

**Comment by Zomboided** [comment] 2018-11-02 10:09
I don't see this behaviour.  I've just simulated creating a user with a
space and viewed the resulting OVPN files and everything looks fine.
I need to see a debug log (switch on debug in settings/advanced) here
following a clean install I think.

**Comment by Zomboided** [comment] 2018-11-05 11:03
Fixed in 5.0.7

**Closed by Zomboided** 2018-11-05 11:03 UTC
