### ISSUE TITLE
Connection lock up, still says connected. LibreELEC, Pi.

### ISSUE THREAD

**Issue by Pulseeey** [Zomboided/service.vpn.manager#142] opened 2018-04-03 19:00 UTC
First of all, thank you for your work on this addon.

I've noticed this occurring on various SBC devices, LibreELEC latest and latest manager. Fresh installs.

It's rather odd what's occurring, it seems the VPN just locks up after a while and can only be restored by reconnecting or restarting, which is rather problematic for the remote devices for family members that rely on VNC going through the VPN. The manager still says it's connected to the VPN. (Can't use the status feature, but the disconnect/connect panel shows it as green/connected still). As does the VPN in the OpenVPN status log, coincidentally, always the same 10.8.0.10 IP assigned to the ones that are "faulty" so that may just be an OpenVPN thing where it's not removing it from the list.

VPN is OpenVPN using AES-128-CBC, ping checks every 30 seconds and TLS regen set to 4 hours instead of 1. It works as expected until it seems you leave the device idling for a good while such as watching normal TV or when the TV is off overnight but it's rather inconsistent. Which is odd because I would assume Kodi still performs some activities that use the net thus keeping it online, CEC is set to ignore not suspend too.

Below is the Kodi.log, 22:33 is when it was set up. 19:15 the next day is when I noticed it was having problems and began reconnecting from there. Luckily I port forwarded the VNC port and could VNC in using the source IP rather than the VPN.
[Kodi log.txt](https://github.com/Zomboided/service.vpn.manager/files/1872986/Kodi.log.txt)

Here is the VPN server log for the user of the most recent occurrence. Same as above starts when I set up and the end is when I reconnected after noticing. 
[OpenVPN log.txt](https://github.com/Zomboided/service.vpn.manager/files/1872985/OpenVPN.log.txt)

Manager settings: 
![w2xf8](https://user-images.githubusercontent.com/11141528/38270523-8c6804f6-377b-11e8-82ce-d3de2f3f40dd.png)
![mgie8](https://user-images.githubusercontent.com/11141528/38270522-8c4ff9ba-377b-11e8-8119-b7b7c6bac37a.png)

Hope we can work on the cause. :)

**Comment by Zomboided** [comment] 2018-04-03 19:54
I don't see an problem here.  Let me net out the log

This :

```
14:22:47.375 T:1659593632    NONE: VPN Mgr Debug: (Linux) Checking VPN task with pidof openvpn
16:21:16.891 T:1473401760    NONE: Previous line repeats 110 times.
```

means that it's checking your connection and finding no issues - openvpn is still running.

Then something that's a different task number to the service that's doing the checking does this:

```
16:21:16.891 T:1473401760   ERROR: ## LibreELEC Addon ## oe::load_url(https://update.libreelec.tv/updates.php?i=f2f4e49bc70da71a60833865b6b67867&d=LibreELEC&pa=RPi2.arm&v=8.2.4&l=0
                                            ) ## ERROR: (URLError(timeout('timed out',),))
16:21:16.893 T:1473401760   ERROR: Traceback (most recent call last):
                                              File "/home/chewitt/LibreELEC.82-images/build.LibreELEC-RPi2.arm-8.2.4/LibreELEC-settings-0768930/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/oe.py", line 271, in load_url
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                            URLError: <urlopen error timed out>
16:21:16.905 T:1473401760   ERROR: ## LibreELEC Addon ## system::check_updates_v2 ## ERROR: (TypeError('expected string or buffer',))
16:21:16.906 T:1473401760   ERROR: Traceback (most recent call last):
                                              File "/home/chewitt/LibreELEC.82-images/build.LibreELEC-RPi2.arm-8.2.4/LibreELEC-settings-0768930/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/resources/lib/modules/system.py", line 768, in check_updates_v2
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                            TypeError: expected string or buffer
```
but the VPN service keeps on checking :

```
16:21:40.442 T:1659593632    NONE: VPN Mgr Debug: (Linux) Checking VPN task with pidof openvpn
```

And then something else happens here, which looks like some kinda SMB issue (might be really wrong though), which may or may not be related to the previous issue above.

```
16:21:58.689 T:1573909408   ERROR: CCurlFile::Exists - Failed: Timeout was reached(28) for davs://USERNAME:PASSWORD@blank
```

Then it carries on checking and thinks that openvpn is still running

```
16:22:44.692 T:1659593632    NONE: VPN Mgr Debug: (Linux) Checking VPN task with pidof openvpn
18:22:03.696 T:1573909408    NONE: Previous line repeats 111 times.
```

Before getting upset at the file again

```
18:22:03.696 T:1573909408   ERROR: CCurlFile::Exists - Failed: Timeout was reached(28) for davs://USERNAME:PASSWORD@blank
```

And then it carries on checking before I can see you trying to connect and disconnect
```
18:22:41.982 T:1659593632    NONE: VPN Mgr Debug: (Linux) Checking VPN task with pidof openvpn
19:15:23.345 T:1858073504    NONE: Previous line repeats 49 times.
```

The openvpn logs that I can see look fine.  I'm not clued up enough to look at openvpn server logs as I don't run my own, so that's no help.

The fact that it runs for hours without noticing something going away means that I think that the connection is being kept alive, or you're running with the option to automatically restart the connection (don't, let it fail - I can't remember which option this is tho....).  

If you think that the problem is that the connection isn't being kept alive, then there's a ping option in the debug menu which can do this, but as you're doing a user defined here you'll need to look at the ovpn files that are generated to confirm that the ping parameter has made it into the user defined, and is not conflicting with other parameters you've got in there.

The only other thing worth noticing is that you seem to only be going out to ipinfo.io, and I spotted a failure getting the info back here 

```
19:17:28.256 T:1343464352   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider ipinfo.io
19:17:28.257 T:1343464352   ERROR: VPN Mgr : (ipinfo.py) <urlopen error timed out>
19:17:28.428 T:1343464352    NONE: VPN Mgr Debug: Got response, IP is error response time in seconds is 40
19:17:28.428 T:1343464352   ERROR: VPN Mgr : (common.py) Didn't get a good response from ipinfo.io
19:17:28.490 T:1343464352    NONE: VPN Mgr Debug: Retrying ipinfo.io, in 3 seconds
```

Make sure you've got the IP providers set to automatic because these can be a bit flaky and cause delays.  Here it looks like it's just not responding which either means that the service is down or you're not routing the traffic.  If it was a DNS problem, it'd have a different error.  And there's a bunch of other calls which appear to work fine.

To debug, you'll need to look at the openvpn log when the system is in a bad state and see how that relates to your openvpn server.  Again, I just don't see any issues with what my add-on is doing here.

**Comment by Zomboided** [comment] 2018-04-03 19:55
And just to add, I have a pair of RPis running all the time, with one getting very sporadic use and I don't see this.  I'm connecting to a provider though, not my own server.

**Comment by Pulseeey** [comment] 2018-04-03 20:08
Thank you, and please, don't think I'm saying your plugin is faulty or anything. Just simply one of the common denominators and thought I'd give you a shout just for clarification.

I do have a ping check enabled on my VPN, though I would find it rather funny if it was actually disconnecting me rather than keeping it alive, unless this is simply because the manager can't keep up or something. So is disabling the server-side keep alive mechanisms better and to allow it to fail?

Ping is enabled in debug menu too, maybe it's conflicting.

It is indeed set to Auto Select for the location server. It seems to always use this when I manually check too. 

Thank you.

**Comment by Zomboided** [comment] 2018-04-03 20:33
Here's the ping code....the stuff in the f.write lines should be output to your ovpn files unless you've already got a ping parameter in there already at which point it assumes you want to do your thing and leaves it well alone.

```
            if not found_ping and addon.getSetting("force_ping") == "true":
                if proto == "tcp":
                    f.write("ping 10\n")
                    f.write("ping-exit 60\n")
                else:
                    f.write("ping 5\n")
                    f.write("ping-exit 30\n")
                f.write("ping-timer-rem\n")
```

It might be that this doesn't work, I'll need to test it again myself sometime.

You should also look for ping-restart and resolv-retry options.  I force resolv-retry to 30 in the import wizard, but if you've not let it fix that, you might have another value that's causing restarts to happen.

**Comment by Pulseeey** [comment] 2018-04-04 10:59
resolv-retry is set to 30 yes, there are no keepalive/ping options set in the client file. Upon disabling keepalive on the server and adding the following to the client ovpn file, the VPN disconnects and reconnects every minute.
ping 10
ping-exit 60

Enabling keepalive prevents this but then it's the same as previous. Perhaps it's wise to use both?

**Comment by Zomboided** [comment] 2018-04-04 11:13
Here's the manual entry for keepalive.

```
--keepalive n m
    A helper directive designed to simplify the expression of --ping and --ping-restart in server mode configurations.

    For example, --keepalive 10 60 expands as follows:

     


         if mode server:
           ping 10
           ping-restart 120
           push "ping 10"
           push "ping-restart 60"
         else
           ping 10
           ping-restart 60
```

keepalive does a ping-restart rather than a ping-exit, which is I guess why you're not seeing a restart happening.  If you look in the openvpn log, I'd bet that you'd see a restart cycle.

The question here is why is your server not responding to pings.  If it was, then the openvpn connection would be kept alive.

**Comment by Zomboided** [comment] 2018-04-07 11:35
Just checked ping with user defined, and it's adding it to the ovpn file just fine.  I'm closing this because I think the problem you're seeing is outside of the add-on

**Closed by Zomboided** 2018-04-07 11:35 UTC
