### ISSUE TITLE
error reading password from private key auth file: PATH

### ISSUE THREAD

**Issue by HeadHunt94** [Zomboided/service.vpn.manager#188] opened 2018-10-31 07:40 UTC
I always get this error message. My Private Key is embedded in my ovpn file i don't get why the manager is looking for one. Once i created a key file with the key from the ovpn file but got thes ame error.
Sorry if its a stupid request. 

thx in advance

**Comment by Zomboided** [comment] 2018-10-31 08:05
Need a log with debug switched on

**Comment by HeadHunt94** [comment] 2018-10-31 19:39
So i hope this is the correct log. 
By the way the openvpn connection works perfectly when i execute it over the console over ssh (putty). I give the path of the ovpn file and give my password and it works. But i would prefer if your app would work. 
In this place thanks for your time!!
[kodi_18-10-31_20-29-41.log](https://github.com/Zomboided/service.vpn.manager/files/2536104/kodi_18-10-31_20-29-41.log)

**Comment by Zomboided** [comment] 2018-10-31 20:07
You've got a password on your key file right?
As opposed to a password to connect to the VPN

**Comment by HeadHunt94** [comment] 2018-10-31 20:13
well the thing is i produced a ovpn file with my raspberry pi on pivpn. and i had to choose a password.
i think its just a password to connect to the vpn but im not sure.

**Comment by HeadHunt94** [comment] 2018-10-31 20:20
if i had one would it be the same? if not then it must be for the connection itself.

**Comment by Zomboided** [comment] 2018-10-31 20:39
They're different - I think one appears to lock the key, I've never used it personally, the usual password combo is needed to authenticate with your provider.  

If you've locked the key (or your VPN provider has), then your problem is a duplicate of https://github.com/Zomboided/service.vpn.manager/issues/60

Otherwise, use the the User Defined wizard and it all should work.  Just upload the ovpn when asked and enter the user/password in the GUI.  If you want to upload the ovpn, etc to the UserDefined directory then you'll need to follow the errors through and work out what it's not working.  I can't do that for you as I don't know what your ovpn files are asking for, or what your directory structure is.

**Closed by Zomboided** 2018-10-31 20:39 UTC

**Comment by HeadHunt94** [comment] 2018-10-31 20:48
well i am using the wizard. i upload the ovpn file and the pass.txt. type my password in and then this error occurs. 
The thing is i also observed that when i use the askpass command the addon doesnt recongnise it. it says in the import log. pass.txt was used 0 times in ovpn file. and it does it for all commands i add like the auth-user-pass command. i triple checked the PATH.

**Comment by Zomboided** [comment] 2018-10-31 20:59
You don't need to supply the pass.txt, it'll get generated.  I think the
issue from your description is that you've a password on the key, which is
a duplicate of the bug I pointed you at.
You can work around this but creating a keypass.txt (or something similar),
putting the credentials in that and hard coding the path in the ovpn.
Creating that should be documented in the openvpn docs.

**Comment by HeadHunt94** [comment] 2018-10-31 21:00
okay thank you for your time

**Comment by HeadHunt94** [comment] 2018-10-31 21:02
hard coding in the ovpn means waht exactly? in the ovpn file? like askpass PATH?

**Comment by Zomboided** [comment] 2018-10-31 21:05
I can't remember what the parameter is for the key password, but yes.  If
you look at the ovpn after it's imported it'll show you an example of a
path.

**Comment by HeadHunt94** [comment] 2018-10-31 21:08
Well yes thats what i do but it seems the manager doesnt recognize the
command.
If i understood you correctly

Am Mi., 31. Okt. 2018, 22:05 hat Zomboided <notifications@github.com>
geschrieben:
