### ISSUE TITLE
Log spamming 

### ISSUE THREAD

**Issue by taaning** [Zomboided/service.vpn.manager#263] opened 2019-11-06 18:11 UTC
While trying to debug another problem, I found that the service.vpn.manager is heavily spamming the log with the following entries.

> 2019-11-06 17:11:38.286 T:3856630496   DEBUG: CSettingsManager: requested setting (label1008) was not found.
> 2019-11-06 17:11:38.286 T:3856630496   DEBUG: CAddonSettings[service.vpn.manager]: failed to find definition for setting label1008. Creating a setting on-the-fly...
> 2019-11-06 17:11:38.286 T:3856630496   DEBUG: CSettingsManager: requested setting (label101) was not found.
> 2019-11-06 17:11:38.286 T:3856630496   DEBUG: CAddonSettings[service.vpn.manager]: failed to find definition for setting label101. Creating a setting on-the-fly...
> 2019-11-06 17:11:38.286 T:3856630496   DEBUG: CSettingsManager: requested setting (label1013) was not found.
> 2019-11-06 17:11:38.286 T:3856630496   DEBUG: CAddonSettings[service.vpn.manager]: failed to find definition for setting label1013. Creating a setting on-the-fly...
> 2019-11-06 17:11:38.286 T:3856630496   DEBUG: CSettingsManager: requested setting (label1045) was not found.
> 2019-11-06 17:11:38.286 T:3856630496   DEBUG: CAddonSettings[service.vpn.manager]: failed to find definition for setting label1045. Creating a setting on-the-fly...

I am using OSMC on a Vero 4K+ 

Opened a thread on the OSMC, [Link](https://discourse.osmc.tv/t/debug-logs-fills-up/82953) 
[Link to the log files.](https://paste.osmc.tv/ixovecuver)

**Comment by Zomboided** [comment] 2019-11-06 18:32
This irritating nonsense (I agree it's poor) is caused by the settings rework in Kodi, I'm not generating these.  I've a build where I've tried to make sure everything has labels, but I'm not convinced it'll fix these as I don't know why Kodi is generating them.......

So closing because I'm not gonna make any more changes until there's some clear direction on how to write settings (last update to the doc I can find is 1.5 years ago, pre 18).  I do need to kick out the build I mentioned, but it's waiting on me doing some testing for another fix

**Closed by Zomboided** 2019-11-06 18:32 UTC

**Comment by malvinas2** [comment] 2019-11-26 20:55
I just want to reinforce how annoying this issue is: The whole log is full of these messages, thus I have to delete the addon every time I want to upload the log for other addon-developers. Otherwise they wouldn't be able to orient themselves within the log to find possible errors caused by their own addon...

**Comment by Zomboided** [comment] 2019-11-26 21:33
Then raise the issue with the Kodi devs...these are not my problems to fix
