### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by tristram23** [Zomboided/service.vpn.manager#18] opened 2016-12-16 20:46 UTC
I am having issues with Invisible browsing VPN and would like to get some support but the OpenElec forum is currently not letting anyone register for new account so that option is not available.
My log files are attached. 
[openvpn_log.txt](https://github.com/Zomboided/service.vpn.manager/files/658199/openvpn_log.txt)
[kodi_16-11-21_21-27-39.txt](https://github.com/Zomboided/service.vpn.manager/files/658201/kodi_16-11-21_21-27-39.txt)
Thanks

**Comment by Zomboided** [comment] 2016-12-16 21:00
It looks like it's failed for a bunch of different reasons.  Keep debug on, do a reset of the ovpn files (settings/utilities), then try again with the right pass/userID and try and connect.  If that fails then upload the kodi log and one of the .ovpn files that has been generated in /storage/.kodi/addons/service.vpn.manager/ibVPN

**Comment by 8472** [comment] 2016-12-16 22:50
Try this:   
Go into add on settings
Reset to default settings
Go to Kodi, System,, Add-ons, My add-ons, Services.    Delete VPN Manager.
Install zomboided repository zip file
Install VPN manager from repository.
Run wizard and enter VPN provider and login/pw credentials.

**Comment by tristram23** [comment] 2016-12-17 09:22
I was not able to find anywhere where I could reset to default settings for add-ons.
I am not sure if it is my build (goodfellas) which is on a Raspberry 3 running LibreELEC, is not showing it but I am not sure if I want to set the whole system back to default.

I followed your first set of instructions and the files are:

[log_ovpn.zip](https://github.com/Zomboided/service.vpn.manager/files/658779/log_ovpn.zip)

**Comment by Zomboided** [comment] 2016-12-17 15:41
You don't need to do much of what 8472 is telling you, resetting the ovpn files as I'd indicated is enough.

There are a couple warnings in the log, which are fine.  This is your problem :
Options error: Unrecognized option or missing parameter(s) in [PUSH-OPTIONS]:1: show-net-up (2.3.10)

I had thought the ovpn files were being generated incorrectly but the problem is caused by ibVPN pushing the show-net-up at your system, which is then not working (or they're not pushing it correctly)

Assuming your system is still it the same state, can you get on the command line, do a cd /storage/.kodi/addons/service.vpn.manager/ibVPN check the pass.txt file still exists and then type "openvpn US - Chicago (UDP).ovpn"  Do you see it connect?  Does it say "Initialisation sequence completed" with no other errors or warnings?  You can pipe this to a log if you need to share it.

If it connects I can make a change to fix this easy enough.

**Comment by severus-2016** [comment] 2016-12-17 18:39
Hello Zomboided,

first of all, thank you for the great add-on.
I got the same error choosing PerfectPrivacy.

> Does it say "Initialisation sequence completed" with no other errors or warnings?

Yes, if i try the manual way via ssh (using a PerfectPrivacy node), it works without warnings.
Can you please fix it?

Another quick info that could be useful to address the problem: for some reasons it works with servers that are NOT ipv6.
Hope this helps.

Thank you so much!

**Comment by Zomboided** [comment] 2016-12-17 19:01
severus, do you get exactly the same problem, ie, esp the bit in bold?
Options error: Unrecognized option or missing parameter(s) in [PUSH-OPTIONS]:1: **show-net-up (2.3.10)**

Thanks for testing it out.  I'm assuming that you see the same error when you try it manually?

**Comment by severus-2016** [comment] 2016-12-17 19:52
Thank you for the quick reply, Zomboided.
You are right, the error is different:

> Error connecting to VPN, unrecognised option.
> Disable block-outside-dns in debug menu, reset ovpn files and retry. Or check log and review ovpn file in use.

Actually i don't even see the "block-outside-dns" option on the debug menu (i'm running the latest release of the plugin).
I've tried to reset the ovpn files and to re-upload them, unsuccessfully.

Then i made some tests and i tried 3 different VPN connections:
- ExpressVpn works
- PerfectPrivacy and Ibvpn don't work (i get the above error message)

So i tried all the releases and the last one that works with PerfectPrivacy and Ibvpn was the 1.7.0.

> I'm assuming that you see the same error when you try it manually?

The manual way works (it says "Initialization Sequence Completed" and so on..).
After this, if i choose "display vpn status" from kodi i see the correct ip of the PerfectPrivacy server.

Hope this helps.
Thank you!

**Comment by Zomboided** [comment] 2016-12-17 19:57
You'll only see the option on Windows, so that's fine.
So for PerfectPrivacy, exactly what error message do you see?  Can you post the log.
And yes, it makes perfect sense it worked with 1.7.0, 1.8.0 is when I introduced a check for bad options...looks like I was being a bit too aggressive

**Comment by tristram23** [comment] 2016-12-17 21:29
When I try doing as you said I get the following error:
-sh: syntax error: unexpected "("

I can ls and see all the files but I keep getting error above.

**Comment by Zomboided** [comment] 2016-12-17 21:32
Wrap quotes around the command or use tab complete

**Comment by severus-2016** [comment] 2016-12-17 21:43
Sure, here you have to log:

```
20:09:46 2763.249268 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 OpenVPN 2.3.10 armv7ve-libreelec-linux-gnueabi [SSL (OpenSSL)] [LZO] [EPOLL] [IPv6] built on Jun 22 2016
20:09:46 2763.249268 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 library versions: LibreSSL 2.2.6, LZO 2.09
20:09:46 2763.249268 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 WARNING: file '/storage/.kodi/addons/service.vpn.manager/PerfectPrivacy/pass.txt' is group or others accessible
20:09:46 2763.249268 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 WARNING: file '/storage/.kodi/userdata/addon_data/service.vpn.manager/PerfectPrivacy/user_London_(UDP).key' is group or others accessible
20:09:46 2763.249512 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'DHE-RSA-AES256-GCM-SHA384', please use IANA name 'TLS-DHE-RSA-WITH-AES-256-GCM-SHA384'
20:09:46 2763.249512 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'DHE-RSA-AES256-SHA256', please use IANA name 'TLS-DHE-RSA-WITH-AES-256-CBC-SHA256'
20:09:46 2763.249512 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'DHE-RSA-AES128-GCM-SHA256', please use IANA name 'TLS-DHE-RSA-WITH-AES-128-GCM-SHA256'
20:09:46 2763.249512 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'DHE-RSA-AES128-SHA256', please use IANA name 'TLS-DHE-RSA-WITH-AES-128-CBC-SHA256'
20:09:46 2763.249512 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'DHE-RSA-CAMELLIA256-SHA', please use IANA name 'TLS-DHE-RSA-WITH-CAMELLIA-256-CBC-SHA'
20:09:46 2763.249756 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'DHE-RSA-AES256-SHA', please use IANA name 'TLS-DHE-RSA-WITH-AES-256-CBC-SHA'
20:09:46 2763.249756 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'DHE-RSA-CAMELLIA128-SHA', please use IANA name 'TLS-DHE-RSA-WITH-CAMELLIA-128-CBC-SHA'
20:09:46 2763.249756 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'DHE-RSA-AES128-SHA', please use IANA name 'TLS-DHE-RSA-WITH-AES-128-CBC-SHA'
20:09:46 2763.249756 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'CAMELLIA256-SHA', please use IANA name 'TLS-RSA-WITH-CAMELLIA-256-CBC-SHA'
20:09:46 2763.249756 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'AES256-SHA', please use IANA name 'TLS-RSA-WITH-AES-256-CBC-SHA'
20:09:46 2763.250000 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'CAMELLIA128-SHA', please use IANA name 'TLS-RSA-WITH-CAMELLIA-128-CBC-SHA'
20:09:46 2763.250000 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Deprecated TLS cipher name 'AES128-SHA', please use IANA name 'TLS-RSA-WITH-AES-128-CBC-SHA'
20:09:46 2763.250000 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 WARNING: file '/storage/.kodi/addons/service.vpn.manager/PerfectPrivacy/London_ta.key' is group or others accessible
20:09:46 2763.250000 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 Control Channel Authentication: using '/storage/.kodi/addons/service.vpn.manager/PerfectPrivacy/London_ta.key' as a OpenVPN static key file
20:09:46 2763.250000 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 UDPv4 link local: [undef]
20:09:46 2763.250000 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 UDPv4 link remote: [AF_INET]5.187.21.98:1151
20:09:46 2763.250000 T:1640203168  NOTICE: Sat Dec 17 20:08:52 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
20:09:46 2763.250244 T:1640203168  NOTICE: Sat Dec 17 20:08:55 2016 [Server_london.perfect-privacy.com] Peer Connection Initiated with [AF_INET]5.187.21.98:1151
20:09:46 2763.250244 T:1640203168  NOTICE: Sat Dec 17 20:08:58 2016 Options error: unknown --redirect-gateway flag: ipv6
20:09:46 2763.250244 T:1640203168  NOTICE: Sat Dec 17 20:08:58 2016 TUN/TAP device tun0 opened
20:09:46 2763.250244 T:1640203168  NOTICE: Sat Dec 17 20:08:58 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=1
20:09:46 2763.250244 T:1640203168  NOTICE: Sat Dec 17 20:08:58 2016 /sbin/ip link set dev tun0 up mtu 1500
20:09:46 2763.250488 T:1640203168  NOTICE: Sat Dec 17 20:08:58 2016 /sbin/ip addr add dev tun0 10.1.2.249/24 broadcast 10.1.2.255
20:09:46 2763.250488 T:1640203168  NOTICE: Sat Dec 17 20:09:00 2016 add_route_ipv6(): not adding 2000::/3, no IPv6 on if tun0
20:09:46 2763.250488 T:1640203168  NOTICE: Sat Dec 17 20:09:00 2016 Initialization Sequence Completed

```

Do you see something strange?

**Comment by Zomboided** [comment] 2016-12-17 21:44
This : Options error: unknown --redirect-gateway flag: ipv6
is why it's failing.

Thanks both, I've uploaded 2.2.6 to the repo and as a new release.  Can you let me know if it works for you and I'll close this.

**Comment by tristram23** [comment] 2016-12-17 21:56
It works for me now, Thanks for your time, it is greatly appreciated.

**Closed** 2016-12-17 22:01 UTC

**Comment by severus-2016** [comment] 2016-12-17 22:39
Yes, it works!
Thank you for your fantastic support, Zomboided.
