### ISSUE TITLE
DNS leak? Cannot see setting to change DNS

### ISSUE THREAD

**Issue by Ozman** [Zomboided/service.vpn.manager#367] opened 2022-06-11 04:35 UTC
I am using Nord VPN to access the U.K. However the UK service is able to detect that I am from outside the UK and so block my access. I cannot see any setting within the VPN Manager to allow me to specify the DNS addresses of Nord. I am sorry if this has been addressed elsewhere on your site but I cannot find the answer.

Thank you very much for providing this app.

**Comment by Zomboided** [comment] 2022-06-11 09:34
There’s not one, DNS is usually pushed by your VPN. I think there’s a DNS setting in Kodi or LibreELEC somewhere if you want to try and change it there.

I’m not clear this is your problem though, i think services are usually blocked by IP address

Either way nothing I can fix here

**Comment by peno64** [comment] 2022-06-11 10:30
Alot of services can detect that you connect via a vpn. For example Netflix does that and as such they also don't allow to use their services. Maybe that is more your problem.

**Comment by Ozman** [comment] 2022-06-12 21:01
Thanks for the replies. I altered my dns settings in kodi running CoreElec but that made no difference. The UK service still detected I was outside the UK. The strange thing is that I have two other televisions in different parts of the house, one with an Amazon Fire Stick and one with Google Chromecast TV. Both connect to Nord VPN and to the UK service no problem. So it seems to me that the problem is with my Kodi setup. I have given up for now, having spent many hours trying to solve this. Thanks again.

**Comment by Zomboided** [comment] 2022-06-13 06:51
You could understand what server the other boxes are connecting to and use that with the User Defined option.  The problem is that Nord will probably go and change their servers to work around being blocked and you'll have to keep doing this.
Either way, closing it because I don't think it's an issue with the add-on as it's using settings downloaded from Nord.

**Closed by Zomboided** 2022-06-13 06:51 UTC
