### ISSUE TITLE
Still having DNS issues. Stuck in checking location info...

### ISSUE THREAD

**Issue by docwhite** [Zomboided/service.vpn.manager#242] opened 2019-06-29 08:16 UTC
Dear Zomboided, thanks for your effort with this plugin it's nicely designed!

However, after setting up a fresh install of OSMC on a Raspberry Pi 3 I am facing some issues when setting it up for NordVPN.

It all goes well until it gets stuck in `Connected, checking location info...` Which clearly seems to point to DNS issues. If I ssh into the raspberry at that point and ping `google.com` it doesn't work, it thinks forever. Then after minutes I get `Profile is Spain, but either there's a DNS issue or some other network problems. You may not be able to access other internet resources until you fix this.`

I tried the DNS fix option and had no luck, I even restarted the system after applying the fix.

Do you know how can I debug this a bit more? I struggle to find the logs of OpenVPN, how do you show them on that `VPN Log` window, do you read them from the stdout? Or do they persist on a file? Anyway on the logs there's nothing unusual (I can see no ERROR logs, I can see the IP route tables being constructed OK, and it finishes with Initialization Sequence Completed).

Any ideas for helping me collect more information to diagnose this?

Thanks so much.

**Comment by Zomboided** [comment] 2019-06-29 08:58
According to the ovenvpn team, it's not the job of openvpn to set the DNS
server after connection.  I understand this view, they provide up and down
scripts to do this.  The fix tries to use the up and down scripts to do
this, but requires that the right set of packages are installed.  You can
read more about the requirements here
https://github.com/Zomboided/service.vpn.manager/wiki/07.-Advanced-Options#potential-dns-fix-linux-only

However, what's confusing to me is that in seemingly similar environments,
some people will see this problem and some people will not.  I've done
extensive testing of Nord (on a PI3, albeit with LibreELEC) and NEVER saw
this problem.

In terms of diagnosing it...the issue is that you don't have a path to an
active DNS server.  So maybe you force your DNS to always be the DNS of
your VPN provider in the GUI (only briefly used OSMC, not sure if it's an
option like it is for LE).  Or you can make the up/down scripts work to
call the resolve scripts mentioned in the link.

I'm goign to close this because it's not an issue with the add-on and other
than what I've provided, I'm not sure I can be any more help.  You might
get more luck googling around openvpn and dns servers, and then trying to
fix this via the command line before moving to fix it using scripts.  If
you fix it and think there's something better I could be doing in the
add-on, then re-open this and I'll consider it.

**Closed** 2019-06-29 08:58 UTC

**Comment by docwhite** [comment] 2019-06-29 15:11
Thanks for your detail response!

> The fix tries to use the up and down scripts to do this, but requires that the right set of packages are installed.

What set of packages do you speak about: killall pidof and openvpn? I can see the update-resolve-conf file in my installation.

Yeah I agree it doesn’t have to do with the plug in. I will do it again on another Pi that has an older Kodi. 

Thanks again.

**Comment by Zomboided** [comment] 2019-06-30 06:33
The dns fix tries to determine if you’re running systemd and if you are it uses https://github.com/jonathanio/update-systemd-resolved rather that update-resolv-conf.

**Comment by alumbs** [comment] 2019-07-04 01:13
The fix that worked for me (From NordVpn was to change my dns servers to point to the NordVpn dns server). Here are the instructions that worked for me:

Open the Terminal and type in:

sudo su

You will be asked for your login password, please type it in and press enter.

Then copy and paste these commands, pressing enter after each one:
cp /etc/resolv.conf /etc/resolv.old.conf

rm -r /etc/resolv.conf

echo -e "nameserver 103.86.96.100""\n""nameserver 103.86.99.100" >> /etc/resolv.conf

chattr +i /etc/resolv.conf

reboot now

**Comment by docwhite** [comment] 2019-07-04 18:34
@alumbs That worked! Thanks a lot!

I have a question though... If I disconnect the VPN, will the DNS changes you make cause any problems if not using the NordVPN?

Good stuff :)

**Comment by alumbs** [comment] 2019-07-04 18:58
@docwhite the dns changes should not affect much.

If it does, simply delete your /etc/resolv.conf file and rename the /etc/resolv.old.conf file back to /etc/resolv.conf (i.e. putting back your original resolv.conf file that we saved as a backup) :)
