### ISSUE TITLE
DNS Issue Lubuntu 17.10

### ISSUE THREAD

**Issue by Morphy99** [Zomboided/service.vpn.manager#129] opened 2018-01-24 22:44 UTC
Having problems setting up PIA in 17.10. Everything completes up to the point of checking location info and it hangs for a few seconds before coming with a provider unknown and IP no info.
From what I can tell is DNS isn't being assigned correctly. Can ping IP's ok but nothing resolves. I believe this is down to some changes in 17.10 but not too sure as a bit of a noob when it comes to linux.

I've found [this](https://aaronhorler.com/articles/openvpn-17.10-dns-leak.html) link which along with setting up ovpn manually [here](https://www.privateinternetaccess.com/forum/discussion/23272/solved-lubuntu-pia-client-doesnt-connect-to-vpn) seems to work.

Also using this ovpn in VPN Manager as a user defined connection also works.

**Comment by Zomboided** [comment] 2018-01-25 08:44
You need to follow the install instructions for Linux on the wiki. I suspect you're missing some packages.

**Comment by Zomboided** [comment] 2018-01-29 11:04
Closing because not a VPN Mgr issue

**Closed** 2018-01-29 11:03 UTC

**Comment by Morphy99** [comment] 2018-02-01 18:53
I followed the instructions on the wiki and everything is installed as far as I know. Openvpn works fine so not sure how this isn't a VPN Manager issue?

**Comment by Zomboided** [comment] 2018-02-01 20:28
It's not a vpn mgr problem because "all" vpn mgr does is call openvpn - which has reported its connected if you're seeing the info screen, followed by using an http call over that link to validate where the connection is located.  Either something is blocking that connection, or openvpn isn't working properly or you're trying to use a op location service that's blocked for you (which you'd need to try to do as it cycles round different services).

I'm happy to look at a full debug log but I think other people have seen problems with this Linux build too. I dunno that I'm gonna tell you anything I've not said before, and I'm not gonna debug your Linux environment.

**Comment by Morphy99** [comment] 2018-02-01 21:52
I think it is something specific with this linux build but I'm curious what. If you can't help no probs but if I can help you improve the addon for other potential users of this build then all the better right? 
So anyway, the ovpn file below works fine from the command line and I've noticed some differences to the TEMPLATE.TXT which I'm guessing is what the addon is using? 

`client
dev tun
proto udp
remote germany.privateinternetaccess.com 1198
resolv-retry infinite
nobind
persist-key
persist-tun
cipher aes-128-cbc
auth sha1
tls-client
remote-cert-tls server
auth-user-pass user-pass.txt
comp-lzo
verb 1
reneg-sec 0
crl-verify /etc/openvpn/crl.rsa.2048.pem
ca /etc/openvpn/ca.rsa.2048.crt
disable-occ
dhcp-option DNSSEC allow-downgrade
dhcp-option DOMAIN-ROUTE .

script-security 2
setenv PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
up /etc/openvpn/scripts/update-systemd-resolved
down /etc/openvpn/scripts/update-systemd-resolved
down-pre`

The last few lines from "dhcp-option..." onwards were added after reading [this](https://aaronhorler.com/articles/openvpn-17.10-dns-leak.html) and seem to make the difference.

Adding this ovpn file as a custom provider also works.

If you can see anything obvious or suggest a route to go down to troubleshoot further I'd be most grateful :)

This is the openvpn.log with debugging:
`Thu Feb  1 21:29:42 2018 WARNING: file '/home/kodi/.kodi/addons/service.vpn.manager/PIA/pass.txt' is group or others accessible
Thu Feb  1 21:29:42 2018 OpenVPN 2.4.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul  3 2017
Thu Feb  1 21:29:42 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Thu Feb  1 21:29:42 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]185.225.208.12:1197
Thu Feb  1 21:29:42 2018 Socket Buffers: R=[212992->212992] S=[212992->212992]
Thu Feb  1 21:29:42 2018 UDP link local: (not bound)
Thu Feb  1 21:29:42 2018 UDP link remote: [AF_INET]185.225.208.12:1197
Thu Feb  1 21:29:42 2018 TLS: Initial packet from [AF_INET]185.225.208.12:1197, sid=03c70a64 c1734317
Thu Feb  1 21:29:42 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Feb  1 21:29:42 2018 VERIFY OK: depth=1, C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private Internet Access, CN=Private Internet Access, name=Private Internet Access, emailAddress=secure@privateinternetaccess.com
Thu Feb  1 21:29:42 2018 VERIFY KU OK
Thu Feb  1 21:29:42 2018 Validating certificate extended key usage
Thu Feb  1 21:29:42 2018 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Feb  1 21:29:42 2018 VERIFY EKU OK
Thu Feb  1 21:29:42 2018 VERIFY OK: depth=0, C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private Internet Access, CN=82f0e38c1d9c5391f17c5a0840603f42, name=82f0e38c1d9c5391f17c5a0840603f42
Thu Feb  1 21:29:43 2018 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Thu Feb  1 21:29:43 2018 [82f0e38c1d9c5391f17c5a0840603f42] Peer Connection Initiated with [AF_INET]185.225.208.12:1197
Thu Feb  1 21:29:44 2018 SENT CONTROL [82f0e38c1d9c5391f17c5a0840603f42]: 'PUSH_REQUEST' (status=1)
Thu Feb  1 21:29:44 2018 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 209.222.18.222,dhcp-option DNS 209.222.18.218,ping 10,comp-lzo no,route 10.50.10.1,topology net30,ifconfig 10.50.10.6 10.50.10.5,auth-token'
Thu Feb  1 21:29:44 2018 OPTIONS IMPORT: timers and/or timeouts modified
Thu Feb  1 21:29:44 2018 OPTIONS IMPORT: compression parms modified
Thu Feb  1 21:29:44 2018 OPTIONS IMPORT: --ifconfig/up options modified
Thu Feb  1 21:29:44 2018 OPTIONS IMPORT: route options modified
Thu Feb  1 21:29:44 2018 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Thu Feb  1 21:29:44 2018 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Thu Feb  1 21:29:44 2018 Data Channel Encrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Feb  1 21:29:44 2018 Data Channel Decrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
Thu Feb  1 21:29:44 2018 Data Channel Decrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Feb  1 21:29:44 2018 ROUTE_GATEWAY 192.168.0.1/255.255.255.0 IFACE=enx000ec6817901 HWADDR=00:0e:c6:xx:xx:xx
Thu Feb  1 21:29:44 2018 TUN/TAP device tun0 opened
Thu Feb  1 21:29:44 2018 TUN/TAP TX queue length set to 100
Thu Feb  1 21:29:44 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Thu Feb  1 21:29:44 2018 /sbin/ip link set dev tun0 up mtu 1500
Thu Feb  1 21:29:44 2018 /sbin/ip addr add dev tun0 local 10.50.10.6 peer 10.50.10.5
Thu Feb  1 21:29:44 2018 /sbin/ip route add 185.225.208.12/32 via 192.168.0.1
Thu Feb  1 21:29:44 2018 /sbin/ip route add 0.0.0.0/1 via 10.50.10.5
Thu Feb  1 21:29:44 2018 /sbin/ip route add 128.0.0.0/1 via 10.50.10.5
Thu Feb  1 21:29:44 2018 /sbin/ip route add 10.50.10.1/32 via 10.50.10.5
Thu Feb  1 21:29:44 2018 Initialization Sequence Completed`

**Comment by Zomboided** [comment] 2018-02-01 23:32
Sure, so what this link is saying is that the DNS isn't updated when the
VPN is connected, and thus the IP info service can't be found (which would
reported in the Kodi log), and you see unknown, as you've observed.  This
is all working as designed.  The issue is that you have an interesting
behaviour with your chosen version of Linux for some reason (either by
design or a bug) as this doesn't happen with other distros (e.g. I use
LibreELEC with PIA)

The extra lines you've added seem to force the update to DNS when the
connection is started and finished (this is the up and down lines you
see).  It would make sense that everything works once you've fixed the DNS
servers.

I'm not going to write code to work around what I currently believe is a
bug in the underlying OS, especially when that bug appears not to be in
other versions of Linux

Your options are :

Either use the built in up and down scripts
https://github.com/Zomboided/service.vpn.manager/wiki/07.-Debug-Options#enable-updown-scripts
which may be too limited as it'll not let you add the other VPN options
(I've no clue what the dhcp options do and I haven't looked them up in the
manual).

Or override the PIA TEMPLATE.txt
https://github.com/Zomboided/service.vpn.manager/wiki/10.-Updating-VPNs
which will allow you add the extra lines you need, yet still get updates
for the PIA locations.

Or you can go the route of changing all of the PIA supplied files and use
the import wizard as you've done with the ovpn file you've shared.

Or use a version of Linux that doens't have this behaviour...which may not
be acceptable to you for other reasons.

I'll share a link to this conversation in the troubleshooting section for
others to find.  Thanks for following up.

**Comment by Morphy99** [comment] 2018-02-03 15:19
Thanks for the info. I've overridden the TEMPLATE.txt in userdata with the extra lines and reset the VPN provider files as instructed and this all works fine now. Thanks for the workaround :+1:
