### ISSUE TITLE
Weird reconnect behaviour shown as paused filtering

### ISSUE THREAD

**Issue by Markman-B** [Zomboided/service.vpn.manager#291] opened 2020-05-24 20:24 UTC
Hi, my IPTV provider does not allow vpn connections. Therefore I'd like to set up a Window ID filter range for live tv. I've entered 10600 as start value and 10805 for end value. I've clicked on OK to save the settings. I can see the ID range in light gray text as long as the connection filtering windows is open. However when I close the OpenVPN connection filtering window and reopen the connection filtering window, the value 10600-10805, is no longer visible. I've checked the settings.xml file and don't see the value 10600-10805 either.

I don't dare to test the connection filtering by Windows ID. My IPTV provider will ban my ipadres when a VPN is running.

I'm using
VPN Manager for OpenVPN 6.3.4
PVR IPTV Simple Client 3.9.8.1
Kodi Leia 18.6.
OS CoreElec

EDIT 1: it seems I had to restart Kodi. 
EDIT 2: Filtering by Window ID range works fine. Awesome!

**Comment by Zomboided** [comment] 2020-05-24 22:26
Worked for me without restarting Kodi, I just checked...glad everything is fine though.
You can also create "FAKECONNECTION.txt" in the userdata/addon-data/service.vpn.manager/ which will let you see the behaviour of any filtering by simulating the connection to the VPN without actually connecting.

**Comment by Markman-B** [comment] 2020-05-25 11:58
Thanks for your support. Appreciate it. It's working fine now. What setting would you recommend to avoid the vpn connection is running or becoming active while the ip channel list is retrieving an update in the background? The update procedure for ip channels takes place on every fresh Kodi start. Can I enable "Connect VPN Before Kodi Starts"(currently set to disabled), or should I set "Delay All Connections Starting"? (currently set to 180s)

Regards,
Mark

**Comment by Zomboided** [comment] 2020-05-25 13:01
Either works. One will let you avoid a vpn to get the channels, which maybe important, the other will establish a vpn connection before you boot so that it’s there when you get the channels.

**Comment by Markman-B** [comment] 2020-05-25 15:35
Not sure if I understand you correctly. The vpn connection should not be running while my ipvt client, is updating the channel list from the iptv server. This happens immediately while Kodi starts. I did not find  a setting to disable the channel update procedure, or to set it to manually. I'd like to avoid an iptv-ban. So I assume, it's not wise to enable "Connect VPN before Kodi starts"?

**Comment by Zomboided** [comment] 2020-05-25 17:53
Right, you should run as default off and then only enable it for addons
where you need a VPN

**Comment by Markman-B** [comment] 2020-05-28 13:00
Thanks for your support. Do you accept PayPal donations?

And can you explain the following behaviour? Yesterday I cleaned the cache for the Extended Info addon version 5.60. 
Immediately I got the message "Addon filtering paused". My shortcut F5, to show the connection table did not work. I had to restart Kodi to enable the VPN connection. I haven't configured addon filters, so I wonder why I received that message.  There could be a good reason for it off course

**Comment by Zomboided** [comment] 2020-05-28 14:57
Sure, PayPal to mattedsmith@gmail.com would be appreciated (and spent on
beer).

Almost the only way to receive the message is if you've paused the
filtering, which you can see if you go into the addon and check the icon
displayed with the last line.  If you then subsequently go to another
window (which your short cut would have done), then it'll remind you that
it's paused.  It's not clever enough to see whether you actually have any
filters.  It'll just do this once, but there might be a bug there that if
you unpause it, it forgets to not tell you.

Also, pausing the filtering will not terminate any active connection (or
start one up) - it'll just stop it from changing to another connection.

If it keeps doing this, open a new issue with a log and I'll look at it.

**Comment by Zomboided** [comment] 2020-05-28 16:52
Thanks for the cash dude, really appreciate the sentiment!

**Comment by Markman-B** [comment] 2020-05-28 20:59
Enjoy the small donation.

I think it's a bug. The VPN connection is not being paused, but disconnected.
 
Are you able to reproduce the issue? If you've Open Extended Info 5.60 installed on your system, go to the Extended Info addon settings and clear cache. You can find it under the General Tab.

I've enabled "Enable debug for just this addon, but the Open VPN Manager addon doesn't respond anymore after clearing the Extended Info cache. I can't view or copy the logfile. I can only provide a complete Kodi logfile I hope I did everything correct.

https://paste.ubuntu.com/p/mxfYQPBxJ7/

**Comment by Zomboided** [comment] 2020-05-28 21:34
It's trying to connect to a profile that doesn't exist.  Can you share your
settings.xml with me from
/storage/.kodi/userdata/addon_data/service.vpn.manager/resources please?
Clear the password and userID from the file, but please don't mess with
anything else in there.

**Comment by Markman-B** [comment] 2020-05-28 22:20
Sure, there's was no password or userID in the settings.xml file.
https://www.dropbox.com/s/lepamjnzpfzcabi/settings.xml?dl=0

**Comment by Zomboided** [comment] 2020-05-29 19:48
I can see something is wrong here as it keeps thinking it needs to reconnect.  I think I need to recreate but please leave the settings.xml on Dropbox for now

**Comment by Markman-B** [comment] 2020-05-29 20:04
No need to hurry buddy, take your time.

**Comment by Zomboided** [comment] 2020-05-30 14:08
Looks like whatever extendedinfo was doing was causing the system to blow away processes and windows.  Never seen this before, normally any process killing is limited to the addon that's causing problems.

If this happens now, it'll just reconnect to the first VPN because I have no clue what was going on before as it's all be killed/cleareed.  If it's the wrong VPN, then the filtering *should* fix this eventually.  And if it's disconnected, then it shouldn't be an issue.  Fixed in 6.3.5, happy for you to give it a go as I never actually managed to recreate what you saw, but could see behaviour in the logs.

Also, I think you said that you didn't want to run a VPN initally.  Right now it's connecting before boot and because of that it's ignoring the delay connection (by design - the two are exclusive).  You should switch off connect before boot to get the delay connection to work.  This option is on the monitor tab.

**Closed by Zomboided** 2020-05-30 14:08 UTC

**Comment by Markman-B** [comment] 2020-05-30 15:23
Thanks for the update and advice. I've just updated to the new version. I'll test it thoroughly and will let you know my findings.

Probably bad coding in the Extended Info addon. This addon hasn't been updated for months, but my AeonMQ7 skin depends on it.
